<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- Created by GNU Texinfo 6.7, http://www.gnu.org/software/texinfo/ -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Exception Handling in C (SICStus Prolog)</title>

<meta name="description" content="Exception Handling in C (SICStus Prolog)">
<meta name="keywords" content="Exception Handling in C (SICStus Prolog)">
<meta name="resource-type" content="document">
<meta name="distribution" content="global">
<meta name="Generator" content="makeinfo">
<link href="index.html" rel="start" title="Top">
<link href="Predicate-Index.html" rel="index" title="Predicate Index">
<link href="index.html#SEC_Contents" rel="contents" title="Table of Contents">
<link href="Calling-Prolog-from-C.html" rel="up" title="Calling Prolog from C">
<link href="Reading-a-goal-from-a-string.html" rel="next" title="Reading a goal from a string">
<link href="Signal-Handling.html" rel="prev" title="Signal Handling">
<style type="text/css">
<!--
a.summary-letter {text-decoration: none}
blockquote.indentedblock {margin-right: 0em}
div.display {margin-left: 3.2em}
div.example {margin-left: 3.2em}
div.lisp {margin-left: 3.2em}
kbd {font-style: oblique}
pre.display {font-family: inherit}
pre.format {font-family: inherit}
pre.menu-comment {font-family: serif}
pre.menu-preformatted {font-family: serif}
span.nolinebreak {white-space: nowrap}
span.roman {font-family: initial; font-weight: normal}
span.sansserif {font-family: sans-serif; font-weight: normal}
ul.no-bullet {list-style: none}
-->
</style>


<link href="texinfo.css" rel="stylesheet" type="text/css">
</head>

<body lang="en">
<span id="Exception-Handling-in-C"></span><div class="header">
<p>
Next: <a href="Reading-a-goal-from-a-string.html" accesskey="n" rel="next">Reading a goal from a string</a>, Previous: <a href="Calling-Prolog-Asynchronously.html" accesskey="p" rel="prev">Calling Prolog Asynchronously</a>, Up: <a href="Calling-Prolog-from-C.html" accesskey="u" rel="up">Calling Prolog from C</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Predicate-Index.html" title="Index" rel="index">Index</a>]</p>
</div>
<hr>
<span id="Exception-Handling-in-C-1"></span><h4 class="subsection">6.5.5 Exception Handling in C</h4>
<span id="index-exception-handling-in-C"></span>

<span id="index-exception-term-1"></span>
<span id="index-term_002c-exception-1"></span>
<p>When an exception has been raised, the functions <code>SP_query()</code>,
<code>SP_query_cut_fail()</code> and <code>SP_next_solution()</code> return
<code>SP_ERROR</code>.  To access the <em>exception term</em> (the argument
of the call to <code>raise_exception/1</code>), which is asserted when the
exception is raised, the function <code>SP_exception_term()</code> is used.
As a side effect, the exception term is retracted, so if
your code wants to pass the exception term back to Prolog, 
then use <code>SP_raise_exception()</code>.
<span id="index-SP_005fexception_005fterm_0028_0029-_0028C-function_0029"></span>
</p>
<p>To raise an exception from a C function called from Prolog, just call
<code>SP_raise_exception()</code>.  Upon return, Prolog will detect that an
exception has been raised, any value returned from the function will be
ignored, and the exception will be passed back to Prolog.
<strong>Please note</strong>: this should only be called right before returning
to Prolog.
<span id="index-SP_005fraise_005fexception_0028_0029-_0028C-function_0029"></span>
</p>
<p>To propagate failure to Prolog, call <code>SP_fail()</code>. Upon return,
Prolog will backtrack.  <strong>Please note</strong>: this should only be called
right before returning to Prolog.
<span id="index-SP_005ffail_0028_0029-_0028C-function_0029"></span>
</p>
<span id="index-SP_005fon_005ffault_0028_0029-_0028C-macro_0029"></span>
<p>Prolog error handling is mostly done by raising and catching exceptions.
However, some <em>faults</em> are of a nature such that when they occur,
the internal program state may be corrupted, and it is not safe to
merely raise an exception.  In runtime systems, the C
macro <code>SP_on_fault()</code> provides an environment for handling faults.
</p>
<span id="index-SP_005fraise_005ffault_0028_0029-_0028C-function_0029"></span>
<p>The function <code>SP_raise_fault()</code> can be used to raise a fault with an
encoded string explaining the reason.
</p>



<div class="logo">
<a href="https://sicstus.sics.se/">
<table><tr><td>&nbsp;</td></tr></table>
</a>
</div>
<div class="node">
<ul class="node">
<li><a href="index.html#Top">User's Manual</a>
<hr>
<li><a href="index.html#TOC">Table of Contents</a>
</ul>
</div>
<hr>
<a HREF="mailto:sicstus-support@sics.se?subject=Documentation%20feedback%20on%20html/sicstus/Exception-Handling-in-C.html&amp;body=Feedback%20on%20documentation%20node%20html/sicstus/Exception-Handling-in-C.html%20in%20User's%20Manual.">Send feedback on this subject.</a>
</body>
</html>
